### PR TITLE
Spring Boot 3 Migration

### PR DESCRIPTION
**Pull request by davidemarcoli**
I've upgraded Spring Boot to Version 3
For that i had to rename the javax imports to jakarta
Furthermore i had to change the WebSecurityConfig because it works slightly different in Spring Security 3

The Application should now function the same as before, but a quick test from @Sashimi4 is appreciated.

### CODE REVIEW

**Review by lazarpe — APPROVED** [review]
LGTM

**Comment by Sashimi4** [comment]
I'll approve it and then check if it works 👍

**Review by Sashimi4 — APPROVED** [review]
😮‍💨🤐🥶😎🥸🤓

**Review by ant0n7 — APPROVED** [review]
LGTM

**Review by Sashimi4 — APPROVED** [review]
LGTM

**Pull request merged**
